Fix feedback applied to closed device
When /set_feedback is called on a closed device, the program does not check
for the availability of the device. This commit adds that check and makes sure
that the device is available before sending feedback messages to the device.
To reproduce this problem, run:

$ roslaunch ds4_driver ds4_driver.launch
$ rostopic pub -r 10 /set_feedback ...  # Appropriate message content

Then disconnect your controller. Before applying this commit, the following
error message is printed:

[ERROR] [/ds4_driver] [1575274223.798851]: bad callback: <bound method ControllerRos.cb_feedback of <ControllerRos(Thread-4, started 140414253643520)>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/naoki/ros/workspaces/kinetic/common/src/ds4_driver/src/ds4_driver/controller_ros.py", line 104, in cb_feedback
    flash_off=to_int(msg.led_flash_off / 2.5) if msg.set_led_flash else None,
  File "/home/naoki/ros/workspaces/kinetic/common/src/ds4_driver/src/ds4_driver/controller.py", line 89, in control
    self._control()
  File "/home/naoki/ros/workspaces/kinetic/common/src/ds4_driver/src/ds4_driver/controller.py", line 100, in _control
    **kwargs)
  File "build/bdist.linux-x86_64/egg/ds4drv/device.py", line 160, in control
    self.write_report(report_id, pkt[send_from:])
  File "build/bdist.linux-x86_64/egg/ds4drv/backends/hidraw.py", line 67, in write_report
    self.fd.write(hid + data)
IOError: [Errno 5] Input/output error